<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="11" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="10102" started-at="2016-06-24T06:59:09Z" finished-at="2016-06-24T06:59:19Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="10102" started-at="2016-06-24T06:59:09Z" finished-at="2016-06-24T06:59:19Z">
      <class name="com.griggi.app.MainTest">
        <test-method status="PASS" signature="beforeTest(org.testng.ITestContext)[pri:0, instance:com.griggi.app.MainTest@27c549b9]" name="beforeTest" is-config="true" duration-ms="1903" started-at="2016-06-24T12:29:09Z" finished-at="2016-06-24T12:29:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@6e4a6525]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="loginBad1()[pri:0, instance:com.griggi.app.MainTest@27c549b9]" name="loginBad1" duration-ms="1411" started-at="2016-06-24T12:29:11Z" description="Logging in. - Too long" finished-at="2016-06-24T12:29:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginBad1 -->
        <test-method status="PASS" signature="loginBad2()[pri:0, instance:com.griggi.app.MainTest@27c549b9]" name="loginBad2" duration-ms="846" started-at="2016-06-24T12:29:12Z" description="Logging in. - Too short" finished-at="2016-06-24T12:29:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginBad2 -->
        <test-method status="PASS" signature="loginBad3()[pri:0, instance:com.griggi.app.MainTest@27c549b9]" name="loginBad3" duration-ms="999" started-at="2016-06-24T12:29:13Z" description="Logging in. - Invalid" finished-at="2016-06-24T12:29:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginBad3 -->
        <test-method status="FAIL" signature="loginGood2()[pri:0, instance:com.griggi.app.MainTest@27c549b9]" name="loginGood2" duration-ms="1957" started-at="2016-06-24T12:29:14Z" description="Verifies that after a bad login, user can enter" finished-at="2016-06-24T12:29:16Z">
          <exception class="org.junit.ComparisonFailure">
            <message>
              <![CDATA[expected:<[The password you entered is not valid.]> but was:<[]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.junit.ComparisonFailure: expected:<[The password you entered is not valid.]> but was:<[]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.griggi.app.MainTest.loginGood2(MainTest.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginGood2 -->
        <test-method status="PASS" signature="loginGood1()[pri:0, instance:com.griggi.app.MainTest@27c549b9]" name="loginGood1" duration-ms="1911" started-at="2016-06-24T12:29:16Z" description="Logging in. - GOOD" finished-at="2016-06-24T12:29:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginGood1 -->
        <test-method status="PASS" signature="dashboardUICheck1()[pri:0, instance:com.griggi.app.MainTest@27c549b9]" name="dashboardUICheck1" duration-ms="77" started-at="2016-06-24T12:29:18Z" description="Check Dashboard UI - 1 (Nav)" finished-at="2016-06-24T12:29:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dashboardUICheck1 -->
        <test-method status="PASS" signature="dashboardUICheck2()[pri:0, instance:com.griggi.app.MainTest@27c549b9]" name="dashboardUICheck2" duration-ms="34" started-at="2016-06-24T12:29:18Z" description="Check Dashboard UI - 2 (Widgets)" finished-at="2016-06-24T12:29:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dashboardUICheck2 -->
        <test-method status="PASS" signature="dashboardUICheck3()[pri:0, instance:com.griggi.app.MainTest@27c549b9]" name="dashboardUICheck3" duration-ms="63" started-at="2016-06-24T12:29:18Z" description="Check Dashboard UI - 3 (Header)" finished-at="2016-06-24T12:29:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dashboardUICheck3 -->
        <test-method status="PASS" signature="verifyLatestNodeURL()[pri:0, instance:com.griggi.app.MainTest@27c549b9]" name="verifyLatestNodeURL" duration-ms="318" started-at="2016-06-24T12:29:18Z" description="Verify the url for the lastest node on dashboard" finished-at="2016-06-24T12:29:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLatestNodeURL -->
        <test-method status="PASS" signature="listOfNodes()[pri:0, instance:com.griggi.app.MainTest@27c549b9]" name="listOfNodes" duration-ms="231" started-at="2016-06-24T12:29:19Z" description="Verify Nav from database - List of nodes" finished-at="2016-06-24T12:29:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listOfNodes -->
        <test-method status="FAIL" signature="nodeAdminDropdownArrow()[pri:0, instance:com.griggi.app.MainTest@27c549b9]" name="nodeAdminDropdownArrow" duration-ms="24" started-at="2016-06-24T12:29:19Z" description="Admin node arrow exists" finished-at="2016-06-24T12:29:19Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.griggi.app.MainTest.nodeAdminDropdownArrow(MainTest.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nodeAdminDropdownArrow -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.griggi.app.MainTest@27c549b9]" name="afterTest" is-config="true" duration-ms="182" started-at="2016-06-24T12:29:19Z" finished-at="2016-06-24T12:29:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.griggi.app.MainTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
